#!/bin/bash

PACKAGE="sc-4.5.0-linux"
DIST_URL="https://saucelabs.com/downloads/$PACKAGE.tar.gz"

set -e

cd /tmp
wget -qO - $DIST_URL | tar -xzv
mkdir -p /usr/local/bin
mv $PACKAGE/bin/sc /usr/local/bin
sudo chmod +u /usr/local/bin
rm -r $PACKAGE
