env:
  SEGMENT_CONTEXTS: "snyk,npm,aws-credentials,ecr,saucelabs"
steps:
  - label: ":hammer: Build and Test"
    command:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install --frozen-lockfile
      - yarn lint
      - yarn test
      - yarn test:ci
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ["node_modules/"]
          s3_bucket_name: "segment-buildkite-cache"
      - docker#v3.3.0:
          image: 528451384384.dkr.ecr.us-west-2.amazonaws.com/analytics.js-integrations-ci
          user: root
          environment:
            - NPM_TOKEN
            - SAUCE_USERNAME
            - SAUCE_ACCESS_KEY

  - wait: ~

  - label: ":hammer: Synk Setup"
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ["node_modules/"]
      - ssh://git@github.com/segmentio/snyk-buildkite-plugin#v1.0.0: 
          runtime: npm

  - wait: ~ 

  - label: ":cloud: Publish"
    branches: master 
    commands:
      - yarn lerna publish from-package --yes
    plugins: 
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ["node_modules/"]
    
