agents:
  queue: general-039

env:
  SEGMENT_CONTEXTS: "snyk,npm,aws-credentials,ecr,saucelabs,npm-publish"
  NODE_BROWSER_IMAGE: "528451384384.dkr.ecr.us-west-2.amazonaws.com/node-browser:22"
  AJS_CI_IMAGE: "528451384384.dkr.ecr.us-west-2.amazonaws.com/analytics.js-integrations-ci:latest"
  CHROME_BIN: "/usr/bin/chromium-browser"

steps:
  - label: ":hammer: Build and Test"
    key: "build"
    branches: "!master"
    command:
      - npm config set "//npmjs.artifacts.twilio.com/artifactory/api/npm/virtual-npm-twilio/:_authToken" $${NPM_TOKEN}
      - yarn install --frozen-lockfile
      - make build
      - yarn test
      - buildkite-agent artifact upload 'build/**/*'
    plugins:
    - docker#v5.12.0:
        image: '${NODE_BROWSER_IMAGE}'
        mount-ssh-agent: true
        mount-buildkite-agent: true
        propagate-environment: true

  - label: ":hammer: Build and Test Master"
    key: "build_master"
    branches: "master"
    command:
      - npm config set "//npmjs.artifacts.twilio.com/artifactory/api/npm/virtual-npm-twilio/:_authToken" $${NPM_TOKEN}
      - yarn install --frozen-lockfile
      - make build
      - yarn test-master
      - buildkite-agent artifact upload 'build/**/*'
    plugins:
    - docker#v5.12.0:
        image: '${NODE_BROWSER_IMAGE}'
        mount-ssh-agent: true
        mount-buildkite-agent: true
        propagate-environment: true

  - label: "SauceLabs"
    key: "sauce_labs"
    branches: "!master"
    soft_fail: true
    command:
      - npm config set "//npmjs.artifacts.twilio.com/artifactory/api/npm/virtual-npm-twilio/:_authToken" $${NPM_TOKEN}
      - yarn install --ignore-engines
      - yarn test:ci
    plugins:
      - docker#v5.12.0:
          image: '${NODE_BROWSER_IMAGE}'
          mount-ssh-agent: true
          propagate-environment: true

  - label: "SauceLabs Master"
    key: "sauce_labs_master"
    branches: "master"
    soft_fail: true
    command:
      - npm config set "//npmjs.artifacts.twilio.com/artifactory/api/npm/virtual-npm-twilio/:_authToken" $${NPM_TOKEN}
      - yarn install --ignore-engines
      - yarn test-master:ci
    plugins:
      - docker#v5.12.0:
          image: '${AJS_CI_IMAGE}'
          mount-ssh-agent: true
          propagate-environment: true

  - label: ":cloud: Upload Assets to stage bucket (from master branch)"
    branches: master
    depends_on:
      - "build_master"
      - "sauce_labs_master"
    command:
      - echo "--- Upload"
      - ./.buildkite/upload.sh

  - label: ":cloud: Upload Assets to stage bucket (from staging branch)"
    branches: staging
    depends_on:
      - "build"
      - "sauce_labs"
    command:
      - echo "--- Upload"
      - ./.buildkite/upload.sh

  - label: ":cloud: Upload Assets to production bucket (from master branch)"
    branches: master
    depends_on:
      - "build_master"
      - "sauce_labs_master"
    command:
      - echo "--- Upload"
      - ./.buildkite/publish.sh