#!/bin/bash

# Usage: publish

set -e

export PATH="ci/bin/:$PATH";
BRANCH=$(git rev-parse --abbrev-ref HEAD);
if [ "$BRANCH" != "master" ]; then {
    >&2 echo "Publish is just allowed from master";
    exit 1;
} fi;

I="$(list-new-releases)";
INTEGRATIONS=( $I );

if [ ${#INTEGRATIONS[@]} -eq 0 ]; then {
    echo Nothing to publish;
    exit 0;
} fi;

for integration in ${INTEGRATIONS[@]}; do {
    echo Publishing $integration;
	npm publish integrations/$integration;
} done;
