#!/bin/bash

# Usage: test-integrations [<browser-type>]

set -e

export PATH="ci/bin/:$PATH";

BRANCH=$(git rev-parse --abbrev-ref HEAD);
if [ "$BRANCH" == "master" ]; then {
    PREVIOUS_COMMIT=$(git rev-parse --verify HEAD~);
    INTEGRATIONS=($(list-updated-integrations --commit=$PREVIOUS_COMMIT));
} else {
    # refs/heads/master
    INTEGRATIONS=($(list-updated-integrations));
} fi;

if [ ${#INTEGRATIONS[@]} -eq 0 ]; then {
    echo Nothing to test;
    exit 0;
} fi;

BROWSER="$1";
if [ "$BROWSER" == "" ]; then {
    BROWSER="phantomjs";
} fi;

karma start karma.conf.js $(printf ",%s" "${INTEGRATIONS[@]}") $BROWSER;
